name: Sync Labels

on:
  workflow_dispatch:
    # for testing
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
      - .github/workflows/sync-labels.yaml
  pull_request:
    branches:
      - main
    paths:
      - .github/labels.yaml
      - .github/workflows/sync-labels.yaml

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.SYNC_LABELS_TOKEN }}
          yaml-file: .github/labels.yaml
